---
:shared:
  :sessions:
    - id
    - session_id
    - data
    - created_at
    - updated_at
  :staff:
    - encrypted_password
    - reset_password_token
    - confirmation_token
    - unlock_token
    - invitation_token
