:shared:
  :application_forms:
    - alternative_family_name
    - alternative_given_names
    - date_of_birth
    - family_name
    - given_names
    - national_insurance_number
    - passport_country_of_issue_code
    - passport_expiry_date
    - registration_number
    - trs_match
  :application_holds:
    - reason_comment
    - release_comment
  :assessments:
    - recommendation_assessor_note
  :email_deliveries:
    - to
    - subject
  :export_audits:
    - filter_params
  :prioritisation_reference_requests:
    - review_note
  :further_information_request_items:
    - failure_reason_assessor_feedback
    - contact_email
    - contact_name
    - review_decision_note
  :mail_delivery_failures:
    - email_address
  :selected_failure_reasons:
    - assessor_feedback
  :selected_failure_reasons_work_histories:
    - assessor_feedback
  :staff:
    - current_sign_in_ip
    - email
    - last_sign_in_ip
    - name
    - unconfirmed_email
  :suitability_record_emails:
    - canonical
    - value
  :suitability_record_names:
    - value
  :suitability_records:
    - date_of_birth
  :support_requests:
    - comment
    - email
    - name
  :teachers:
    - canonical_email
    - current_sign_in_ip
    - email
    - gov_one_email
    - last_sign_in_ip
    - unconfirmed_email
  :uploads:
    - filename
  :work_histories:
    - canonical_contact_email
    - contact_email
    - contact_name
    - email
